import fs from 'node:fs';import zlib from 'node:zlib';import {parseAbi,encodeFunctionData,decodeFunctionResult,decodeEventLog,keccak256,toHex} from 'viem';
const root=new URL('./',import.meta.url),base=new URL('./strategy-current/',root),old=JSON.parse(fs.readFileSync(new URL('target.json',base))),home=JSON.parse(fs.readFileSync(new URL('notebook-evidence/home.json',root))),c=home.contracts;const raw=[];
async function rpc(method,params){await new Promise(r=>setTimeout(r,1600));const request={jsonrpc:'2.0',id:raw.length+1,method,params};const response=await fetch('https://rpc.mainnet.chain.robinhood.com',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request),signal:AbortSignal.timeout(30000)}).then(r=>r.json());raw.push({request,response});if(response.error)throw Error(JSON.stringify(response.error));return response.result;}
const header=await rpc('eth_getBlockByNumber',['latest',false]);
const bank=JSON.parse(fs.readFileSync(new URL('notebook-evidence/bank-abi.json',root))),license=JSON.parse(fs.readFileSync(new URL('notebook-evidence/license-abi.json',root)));
const items=[...['totalBranches','totalPendingLive'].map(functionName=>({address:c.centralBank,abi:bank,functionName})),...['soldToday','remainingToday','currentDay','currentPrice','dayStartPrice','dayFloorPrice','lastSalePrice'].map(functionName=>({address:c.licenseAuction,abi:license,functionName}))];
const mc=parseAbi(['function aggregate3((address target,bool allowFailure,bytes callData)[] calls) payable returns((bool success,bytes returnData)[] returnData)']);
const reply=await rpc('eth_call',[{to:c.multicall3,data:encodeFunctionData({abi:mc,functionName:'aggregate3',args:[items.map(x=>({target:x.address,allowFailure:true,callData:encodeFunctionData(x)}))]})},header.number]);const state=decodeFunctionResult({abi:mc,functionName:'aggregate3',data:reply}).map((x,i)=>({label:items[i].functionName,value:x.success?decodeFunctionResult({...items[i],data:x.returnData}):null}));
const abi=[...bank.filter(x=>x.type==='event'&&['Deposited','BranchesOpened','Withdrawn','EpochSettled'].includes(x.name)),...license.filter(x=>x.type==='event'&&x.name==='LicensesPurchased')];
const range={fromBlock:toHex(BigInt(old.header.number)+1n),toBlock:header.number};
const logs=await rpc('eth_getLogs',[{...range,address:[c.centralBank,c.licenseAuction],topics:[abi.map(x=>keccak256(toHex(x.name+'('+x.inputs.map(i=>i.type).join(',')+')')))]}]);
const events=logs.map(x=>{const d=decodeEventLog({abi,data:x.data,topics:x.topics});return {...x,event:d.eventName,decoded:d.args};});
const ta=parseAbi(['event Transfer(address indexed from,address indexed to,uint256 value)']);
const transfers=(await rpc('eth_getLogs',[{...range,address:c.standard,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef']}])).map(x=>({...x,decoded:decodeEventLog({abi:ta,data:x.data,topics:x.topics}).args}));
fs.writeFileSync(new URL('followup.json.gz',base),zlib.gzipSync(JSON.stringify({scope:'Separate later observation; not merged into the earlier participant snapshot or forecast calibration.',header,state,events,transfers,raw},(_,x)=>typeof x==='bigint'?x.toString():x)));
console.log('Follow-up',Number(BigInt(header.number)),new Date(Number(BigInt(header.timestamp))*1000).toISOString(),state,events.map(x=>x.event).reduce((a,b)=>(a[b]=(a[b]||0)+1,a),{}));
